### ISSUE TITLE
Error when trying to run

### ISSUE THREAD

**Issue by shibdib** [karbowiak/Sluggard#5]
`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'discord.storage' doesn't exist' in /var/www/auth2/Sluggard/library/Db.php:46 Stack trace: #0 /var/www/auth2/Sluggard/library/Db.php(46): PDOStatement->execute(Array) #1 /var/www/auth2/Sluggard/library/permCache.php(19): dbQueryField('SELECT value FR...', 'value', Array, true) #2 /var/www/auth2/Sluggard/plugins/corporationmails.php(62): getPermCache('newestCorpMailI...') #3 /var/www/auth2/Sluggard/Sluggard.php(43): corporationmails->init(Array, Object(Discord\Discord), Object(Zend\Log\Logger)) #4 {main} thrown in /var/www/auth2/Sluggard/library/Db.php on line 46`

**Comment by shibdib** [comment]
oh it's you.. it's Mr Twinkie here :).. moving the corp to discord

**Comment by karbowiak** [comment]
Hey man!

Sadly the bot requires the tables that Rena presents, including some of the data aswell - i'll look into fixing so that it can run standalone! :)

Rena: https://github.com/EVE-KILL/projectRena

**Comment by karbowiak** [comment]
You should be able to run it now WITHOUT the Rena database being present.

Give it a whirl! :)
